#+title: Anna's Bachelorette Party

* High-Level Details

** Travel

Please let Anna know your travel plans.
She can help people coordinate, either to/from the airport or driving to/from Atlanta.
I think there are a total of 13 of us, including Anna.

** Packing

In addition to regular clothes, we will be going paddle boarding on Saturday, you should bring:
- a bathing suit / clothes to get wet in
- a hat
- sunscreen

We will probably eat out for at least one dinner (Friday) and maybe a brunch (Sunday).
We will check out the downtown Nashville bar scene as well (Friday).
Bring appropriate clothes and comfortable shoes.

Saturday my plan is to stay in, play bachelorette games and have a beauty night.
Bring curlers / hair straightener and your favorite nail polish or face mask.
We can try out hair styles for the wedding.

Finally, if there are any decorations or fun 'bachelorette party' items that you think Anna might enjoy, please bring them along!

** House

We are staying at [[https://www.turnkeyvr.com/nashville-tn/4br%252f-3ba][Music House]]: 903A 14th Ave S, Nashville, TN.
The bed situation is: 1 King, 2 Queens, 4 Twins, 1 Sofa Bed.
Check-in is after 3pm; check-out is before 10am.

** Meals

We will probably do a dinner out on Friday evening, before heading to the downtown Nashville bar scene.
We may also do a brunch on Sunday.

Other meals will be prepared by us.
I plan on making a sandwiches and picnic food (olives and cheeses) for our winery tours.
I will also make some breakfast casseroles for the mornings that we are in the house.

* Agenda

| Time         | Event                               |
|--------------+-------------------------------------|
| Thursday     | Arrive in Nashville                 |
| Fri 11:00 am | Pick-up for Winery Tour             |
| Fri 4:30 pm  | Drop-off from Winery Tour           |
| Fri Evening  | Dinner out and down town bar crawl? |
| Sat Morning  | Hangover brunch?                    |
| Sat 1:00pm   | Stand-up Paddle Boarding Tour       |
| Sat Evening  | Night in / games / beauty night     |
| Sun          | Brunch out?                         |
| Sunday       | Leave Nashville                     |

** Winery Tour Details

Booked with [[https://www.barrelsoffunnashville.com][Barrels of Fun]]

- 11:00am - Pickup
- 12:15pm - Winery Stop 1
- 1:15pm - Depart Winery Stop 1
- 2:15pm - Winery Stop 2
- 4:00pm - Depart Winery Stop 2
- 4:30pm - Drop off

We will be able to buy tastings individually at the wineries.
There are no tastings included in the cost.
At the first winery, the tastings are $6 a person.
At the second winery, small pours of 5 wines are $7 and larger pours of 4 wines are $14.

** Paddle Boarding SUP Tour

[[http://www.bigwilliesnashville.com/trip/downtown-nashville-sup-tour-for-bachelor-and-bachelorettes/][SUP Tour Details]]

*Each person will have to sign a waiver*.
You will probably get wet, don't bring a cellphone / camera unless it can get wet.

We should arrive at the Shelby Park Boat Launch in East Nashville at 12:45 pm.
Tour starts at 1:00 pm and takes 1.5 to 2 hours.

I have already booked a group for 10 people... but I think we'll have to add a few.

* Costs

The costs will be managed through SplitWise.
I am also on Venmo, @gonsie.

These costs have already been paid:

|         Total | Details                                 |
|---------------+-----------------------------------------|
|           924 | Winery transportation and gratuity      |
| 50 per person | SUP Tour (no gratuity included)         |
|          2601 | House, possibility of $300 deposit back |
