#+title: Anna's Bachelorette Party

* High-Level Details

** Travel

Please let Anna know your travel plans.
She can help people coordinate, either to/from the airport or driving to/from Atlanta.

** Packing

We will be going paddle boarding on Saturday, you should bring:
- a bathing suit / clothes to get wet in
- a hat
- sunscreen

** House

We are staying at [[https://www.turnkeyvr.com/nashville-tn/4br%252f-3ba][Music House]]: 903A 14th Ave S, Nashville, TN.
The bed situation is: 1 King, 2 Queens, 4 Twins, 1 Sofa Bed.
Check-in is after 3pm; check-out is before 10am.

* Agenda

| Time         | Event                               |
|--------------+-------------------------------------|
| Thursday     | Arrive in Nashville                 |
| Fri 11:00 am | Pick-up for Winery Tour             |
| Fri 4:30 pm  | Drop-off from Winery Tour           |
| Fri Evening  | Dinner out and down town bar crawl? |
| Sat Morning  | Hangover brunch?                    |
| Sat 1:00pm   | Stand-up Paddle Boarding Tour       |
| Sat Evening  | Night in / games / beauty night     |
| Sun          | Brunch out?                         |
| Sunday       | Leave Nashville                     |

** Winery Tour Details

Booked with [[https://www.barrelsoffunnashville.com][Barrels of Fun]]

- 11:00am - Pickup
- 12:15pm - Winery Stop 1
- 1:15pm - Depart Winery Stop 1
- 2:15pm - Winery Stop 2
- 4:00pm - Depart Winery Stop 2
- 4:30pm - Drop off

We will be able to buy tastings individually at the wineries.
There are no tastings included in the cost.
At the first winery, the tastings are $6 a person.
At the second winery, small pours of 5 wines are $7 and larger pours of 4 wines are $14.

** Paddle Boarding SUP Tour

[[http://www.bigwilliesnashville.com/trip/downtown-nashville-sup-tour-for-bachelor-and-bachelorettes/][SUP Tour Details]]

*Each person will have to sign a waiver*.
You will probably get wet, don't bring a cellphone / camera unless it can get wet.

We should arrive at the Shelby Park Boat Launch in East Nashville at 12:45 pm.
Tour starts at 1:00 pm and takes 1.5 to 2 hours.

* Costs

The costs will be managed through SplitWise.
I am also on Venmo, @gonsie.

These costs have already been paid:

|    Total | Details                                 |
|----------+-----------------------------------------|
|      924 | Winery transportation, plus gratuity    |
|      434 | SUP Tour (no gratuity included)         |
|     2601 | House, possibility of $300 deposit back |
|----------+-----------------------------------------|
| 3959 / x | per-person, assuming x people           |
